### ISSUE TITLE
Notification API

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-account-rails#5]
Send notifications to this API to notify users.

User is notified on his/her preferred service (if external service allows multiple).

**Comment by Edholm** [comment]
I think we should revise our position to default to mail. notifyBy should probably be "clearable"

**Comment by lindskogen** [comment]
Don't notify?

**Comment by Edholm** [comment]
Exactly. Also notifyBy should be per subscription service and not global. So I could for example choose mail for News notifications and pushover for GitHub notifications
