### ISSUE TITLE
Editing settings should not require password

### ISSUE THREAD

**Issue by kirayatail** [cthit/chalmersit-account-rails#59]
Tried to set default language, and was prompted that my password was too short.

Changing non-critical settings should not require a password change.
<img width="843" alt="skarmavbild 2016-05-20 kl 11 01 27" src="https://cloud.githubusercontent.com/assets/1055844/15422879/f66ae2f4-1e7a-11e6-969c-73809ae712cf.png">

**Comment by Vilddjur** [comment]
closed by f69844abd8973a3da2c60d178b9252640dd638a1
