### ISSUE TITLE
Unclear authorization message when logging in

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-account-rails#64]
![auth message](https://cloud.githubusercontent.com/assets/3900604/20960746/29e66ea2-bc62-11e6-8b88-976f78207a45.png)

Only happens on first login.

Moved from chalmersit-rails, original author @Meddan

**Comment by lindskogen** [comment]
Configuration issue with account. It needs to be configured to default allow the chalmers.it "application" access

**Comment by Vilddjur** [comment]
Should be fixed now
