### ISSUE TITLE
Low resilience in writable fields

### ISSUE THREAD

**Issue by JonatanGust** [cthit/chalmersit-account-rails#70]
EDIT:
This is about fields in the account settings, tested field is "Nick" which has a ridiculous big char count allowed.
EDIT END;
If anybody missed it, you can basicly have infinity long fields, this is bad as I accidentally proved by posting on chalmers.it (and then it got cross posted to slack). 

I propose that fields should have a reasonable limit, like 100 characters or perhaps 200.

**Comment by lindskogen** [comment]
News articles limited to 200 characters are very short, especially including the length of markdown. I'm all for a limit, but maybe a limit of 1000 chars or so.

**Comment by JonatanGust** [comment]
Yeah, the fields I was talking about are nickname/name and so on, the full text of the messages should allow longer texts.

**Comment by lindskogen** [comment]
Oh.. I did not realise this was in account, my bad 😊

**Comment by JonatanGust** [comment]
Well, it may be a thing to consider for posts aswell

**Comment by JonatanGust** [comment]
This command should exist where the input box's "text field tag" is specified:
:maxlength => 300,
It will limit the actual text to a size of 300 characters (w/o changing ).
[Source](https://stackoverflow.com/questions/16166657/set-maximum-length-in-text-field-in-ror)
Given that it's a problem in RoR

**Comment by lindskogen** [comment]
Good start! But we also need to create a check in backend for this!
