### ISSUE TITLE
Create groups

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-account-rails#8]
Create groups in ou=fkit

**Comment by Edholm** [comment]
Should probably be included  in some kind of admin interface instead of doing it "separately"

**Comment by lindskogen** [comment]
Remember to [`touch`](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-touch) users!

**Comment by Edholm** [comment]
Sounds pervy! ;)

**Comment by lindskogen** [comment]
That's the idea!

**Comment by Edholm** [comment]
Part of #20
